tag: project1
neural-network:
  - config:
      num_layers: 2
      num_neurons:
        - 2
        - 1
      activations:
        - sigmoid
        - sigmoid
        - sigmoid
      loss_function: mean_squared
      learning_rate: 0.3
      epochs: 100
    type: feedforward
dataset: # multiple datasets can be defined
  - config:
      inputs:
        - - 0
          - 0
        - - 0
          - 1
        - - 1
          - 0
        - - 1
          - 1
      outputs:
        - 0
        - 1
        - 1
        - 0
    type: xor
