tag: project1
neural-network:
  - type: 1x1_net
    config:
      neurons_per_layer:
        - 1
      activations:
        - logistic
      loss_function: square_error
      learning_rate: 5
      epochs: 5000
      print_every: 100
  - type: 2x1_net
    config:
      neurons_per_layer:
        - 2
        - 1
      activations:
        - logistic
        - logistic
      loss_function: square_error
      learning_rate: 0.3
      epochs: 10
      print_every: 2
  - type: 2x2_net
    config:
      neurons_per_layer:
        - 2
        - 2
      activations:
        - logistic
        - logistic
      loss_function: square_error
      learning_rate: 0.5
      epochs: 100
      print_every: 100
dataset: # multiple datasets can be defined
  - type: class_example
    config:
      inputs:
        - 0.05
        - 0.1
      desired_outputs:
        - 0.01
        - 0.99
      weights: # 2x2x3 matrix (layer x neuron x weights+bias)
        - - - 0.15
            - 0.20
            - 0.35
          - - 0.25
            - 0.30
            - 0.35
        - - - 0.40
            - 0.45
            - 0.60
          - - 0.50
            - 0.55
            - 0.60
  - type: xor
    config:
      inputs:
        - - 0
          - 0
        - - 0
          - 1
        - - 1
          - 0
        - - 1
          - 1
      outputs:
        - 0
        - 1
        - 1
        - 0
  - type: and
    config:
      inputs:
        - - 0
          - 0
        - - 0
          - 1
        - - 1
          - 0
        - - 1
          - 1
      outputs:
        - 0
        - 0
        - 0
        - 1
